# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: P001water-Blog
email: P001water@163.com

description: "
P001water的blog，致力于红队攻防 安全开发和安全研究
"

#write html inside the double quotes to display in jumbotron
indexdescription: "
<h1>P001water</h1>                               
<h4>红队攻防、安全开发和安全研究</h4>
"

postdescription: "
<h1>P001water</h1>                               
<h4>文章合集</h4>
"

p1toolsdescription: "
<h1>P001water</h1>                               
<h4>正在维护的工具</h4>
"

aboutdescription: "
<h1>P001water</h1>                               
<h4>关于我</h4>
"

lifesharedescription: "
<h1>P001water</h1>                               
<h4>天下行走</h4>
"

baseurl: "" # the subpath of your site, e.g. /blog
url: "p001water.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap